import {
    mdiAccountCircle,
    mdiMonitor,
    mdiFormatListNumberedRtl,
    mdiCogOutline,
    mdiListBox,
    mdiPlaylistEdit,
    mdiCalendarAccount,
    mdiCalendarCheckOutline,
    mdiCalendarEdit,
    mdiDomain,
    mdiShieldCrown,
    mdiViewList,
    mdiViewModule,
    mdiLockCheckOutline,
    mdiAccountSupervisor,
    mdiAccount,
    mdiClipboardList,
    mdiLightbulbOutline,
    mdiBook,
    mdiMap,
    mdiShieldCar,
    mdiPackageVariantClosed,
    mdiCardAccountDetailsStarOutline,
    mdiShieldLock,
    mdiAccountMultipleCheck,
    mdiTicket,
    mdiTicketOutline,
    mdiAccountCreditCard,
    mdiSourceBranch,
    mdiCalendarMonth,
    mdiBriefcase,
} from "@mdi/js";

export default [
    {
        route: "dashboard",
        icon: mdiMonitor,
        label: "Inicio",
        to: "/dashboard",
    },
    {
        route: "profile.edit",
        label: "Perfil",
        icon: mdiAccountCircle,
    },
    {
        label: "Seguridad",
        icon: mdiShieldLock,
        role: "Admin",
        permission: "modulo.seguridad",
        menu: [
            {
                label: "Modulos",
                route: "module.index",
                icon: mdiViewModule,
                permission: "module.index",
            },
            {
                label: "Permisos",
                route: "permissions.index",
                icon: mdiLockCheckOutline,
                permission: "permissions.index",
            },
            {
                label: "Roles",
                route: "perfiles.index",
                icon: mdiAccountSupervisor,
                permission: "perfiles.index",
            },
            {
                label: "Usuarios",
                route: "user.index",
                icon: mdiAccount,
                permission: "user.index",
            },
        ],
    },
    {
        isDivider: true,
    },
    {
        label: "Applicants",
        route: "applicant.index",
        icon: mdiAccountMultipleCheck,
    },
    {
        label: "Jobs",
        route: "job.index",
        icon: mdiBriefcase,
    },
    {
        label: "Zip Codes",
        route: "zipcode.index",
        icon: mdiMap,
    },
    {
        label: "Addresses",
        route: "address.index",
        icon: mdiClipboardList,
    },
    
];
